Enum "insurance_types" {
  "OC"
  "AC"
}

Enum "employee_type" {
  "MANAGER"
  "ADMINISTRATOR"
}

Enum "car_type" {
  "SEDAN"
  "COUPE"
  "SPORTS_CAR"
  "STATION_WAGON"
  "HATCHBACK"
  "CONVERTIBLE"
  "SUV"
  "MPV"
  "MINIVAN"
  "PICKUP_TRUCK"
  "CROSSOVER"
  "VAN"
}

Enum "visit_type" {
  "MAINTENANCE"
  "REPAIR"
}

Enum "department_type" {
  "REPAIR_STATION"
  "DIAGNOSTIC_STATION"
  "AUTOMOTIVE_SHOP"
}
//TODO
Table "insurance" {
  "date_of_expiry" timestamp [pk]
  "coverage" numeric
  "type" insurance_types
  "car_id" int [pk] // from car
}

Table "diagnostic_profile" {
  "car_id" int [pk] // from car
  "visit_id" int
  "employee_id" int
  "engine" varchar
  "body" varchar
  "low_voltage" varchar
  "lighting" varchar
  "breakes" varchar
  "sensors" varchar
  "miscellaneous" varchar
  "conditioning" varchar
}

Table "diagnostic_profile_employee" {
  "employee_id" int [pk]
  "profile_id" int [pk]
}

Table "employee" {
  "employee_id" int [pk, increment]
  "department_id" int
  "type" employee_type //nullable
}

Table "employee_visit" {
  "employee_id" int [pk]
  "visit_id" int [pk]
}

Table "car" {
  "car_id" int [pk, increment]
  "client_id" int 
  "model" varchar
  "brand" varchar
  "type" car_type
}

Table "visit" {
  "visit_id" int [pk, increment]
  "client_id" int
  "car_id" int //reference to diagnostic_profile
  "date_of_visit" timestamp
  "price" numeric
  "type" visit_type
}

Table "action" {
  "visit_id" int
  "action_desc" varchar
}

Table "client" {
  "client_id" int [pk, increment]
  "name" varchar
  "surname" varchar
  "phone_number" varchar
}

Table "workshop" {
  "workshop_id" int [pk, increment]
  "managed_by_department" int
  "type" department_type
  "latitude" float8
  "longitude" float8
}

Table "department" {
  "department_id" int [pk, increment]
  "latitude" float8
  "longitude" float8
}

Table "department_equipment" {
  "department_id" int
  "equipment" varchar
  "quantity" numeric
}

Table "item" {
  "id" int [unique, pk, increment]
  "department_id" int
  "name" varchar
  "quantity" numeric
}

Ref:"car"."car_id" < "insurance"."car_id"

Ref:"car"."car_id" < "diagnostic_profile"."car_id"

Ref:"employee"."employee_id" < "diagnostic_profile"."employee_id"

Ref:"employee"."employee_id" < "diagnostic_profile_employee"."employee_id"

Ref:"diagnostic_profile"."profile_id" < "diagnostic_profile_employee"."profile_id"

Ref:"department"."department_id" < "employee"."department_id"

Ref:"employee"."employee_id" < "visit"."employee_id"

Ref:"client"."client_id" < "visit"."client_id"

Ref:"car"."car_id" < "visit"."car_id"

Ref:"visit"."visit_id" < "action"."visit_id"

Ref:"department"."department_id" < "workshop"."managed_by_department"

Ref:"employee"."employee_id" < "department"."manager_id"

Ref:"employee"."employee_id" < "department"."admin_id"

Ref:"department"."department_id" < "department_equipment"."department_id"

Ref:"department"."department_id" < "item"."department_id"

Ref:"car"."car_id" < "client"."client_id"
