Enum insurance_types {
  oc
  ac
}

Enum employee_type {
  diagnostic_employee
  car_workshop_employee
  automotive_employee
  insurance_employee
}

Enum car_type {
  sedan
  coupe
  sports_car
  station_wagon
  hatchback
  convertible
  suv
  mpv
  minivan
  pickup_truck
  crossover
  van
}

Enum visit_type {
  diagnostic
}

Table insurance as i {
  date_of_expiry datetime [pk]
  //coverage
  type insurance_types
}

Table diagnostic_profile as d_p {
  engine varchar
  body varchar
  low_voltage varchar
  lighting varchar
  breakes varchar
  sensors varchar
  miscellaneous varchar
  conditioning varchar
}

Table employee as e {
  type employee_type
}

Table car as c {
  carId int [pk, increment]
  model varchar
  brand varchar
  type car_type
}

Table visit as v {
  visitId int [pk, increment]
  date_of_visit datetime
  price numeric
  type visit_type
}

Table action as a {
  visitId int
  action_desc varchar
  price numeric
}

Table client {
  clientId int [pk, increment]
  name varchar
  surname varchar
  phone_number varchar
}

Table workshop {
  shopId int [pk, increment]
  location varchar //will be changed to PostGIS
}

Table department {
  departmentId int [pk, increment]
  location varchar //will be changed to PostGIS
}

Table department_equipment {
  departmentId int 
  equipment varchar
}

Table item {
  id int [pk, increment]
  departmentId int
  quantity numeric
}
