version: '3'
services: 
        database:
                image: "postgres"
                environment: 
                        POSTGRES_USER: workshop_admin
                        POSTGRES_PASSWORD: se_not_magical_at_all
                        POSTGRES_DB: workshop_db
                volumes: 
                        - database-data:/var/lib/postgresql/data/
volumes: 
        database-data:
